### PR TITLE
Class util code cleanup

### PR DESCRIPTION
**Pull request by jwaisner**
Cleaned up extra escapes in code.

### CODE REVIEW

**Review by N6REJ — COMMENTED** [review]
Have you tried a page with a domain like j4.local ?

**Comment by jwaisner** [comment]
I dont have one configured. That would be something for you to test :)

**Comment by N6REJ** [comment]
ok.  I always use xyz.local

**Comment by N6REJ** [comment]
test failed:
image
This can be resteted by to going the alias function in apache
image

**Comment by N6REJ** [comment]
image

**Pull request closed without merging**
