### PR TITLE
add: russian translation

### PR DESCRIPTION
**Pull request by cosmopolityan**
## **User description**
Hi, guys! 👋

Great project! <3
Made Russian translation.
I will be grateful if you accept the changes.

Best regards, cosmopolityan.

___

## **Type**
enhancement

___

## **Description**
- This PR introduces a comprehensive Russian translation for the software's user interface.
- It covers general terms, menu items, tools, error messages, and action prompts, ensuring a native experience for Russian-speaking users.
- The translation includes system operations such as starting, stopping, and restarting services, which are crucial for managing the software effectively.
- Errors and warnings are also localized, aiding in better understanding and troubleshooting for Russian users.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>russian.lng</strong><dd><code>Addition of Russian Language Translation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
core/langs/russian.lng

<li>Added a complete Russian translation for the software interface.<br> <li> Included translations for general terms, menu options, tools, errors, <br>and actions.<br> <li> Provided localization for system messages, warnings, and errors.<br> <li> Enhanced user interaction by translating various service and <br>application names.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Bearsampp/Bearsampp/pull/350/files#diff-0a6af7520bd6375e3097d4de482d6a4a77f2100c4f096f01df0c466d4546f26f">+352/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by N6REJ** [comment]
> ## PR Code Suggestions
> Category	Suggestions                                                                                                                                                       
> **Enhancement**	
> Standardize the translation of the term 'service' to avoid user confusion.
> Translate the term 'Apache' to maintain consistency in the translation.
> **Best practice**	
> Use '%d' for numeric placeholders to improve clarity in messages involving numbers.
> **Bug**	
> Correct the spelling mistake for better accuracy and professionalism.
> **✨ Improve tool usage guide:**
> **Overview:** The `improve` tool scans the PR code changes, and automatically generates suggestions for improving the PR code. The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
> 
> * When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L78) related to the improve tool (`pr_code_suggestions` section), use the following template:
> 
> ```
> /improve --pr_code_suggestions.some_config1=... --pr_code_suggestions.some_config2=...
> ```
> 
> * With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:
> 
> ```
> [pr_code_suggestions]
> some_config1=...
> some_config2=...
> ```
> 
> See the improve [usage page](https://pr-agent-docs.codium.ai/tools/improve/) for a comprehensive guide on using this tool.

@cosmopolityan can you examine this validation block and provide feedback please.

**Comment by cosmopolityan** [comment]
@N6REJ
Ok, I'll do it when I wake up 😴
Especially since I unfortunately made a typo in one place (sorry) :(

**Comment by cosmopolityan** [comment]
@N6REJ 
codiumai-pr-agent-pro is really nice tool. I like it!

About validation blocks.

> **Enhancement**
> Standardize the translation of the term 'service' to avoid user confusion.

As a native speaker, I am still of the opinion that the term `служба` would be more appropriate here.
In any case, Russian-speaking users should not have any misunderstandings, as the context of using the term within this software is obvious.
I have seen both the use of the term `служба` and the term `сервис` in software in Russian.

> Translate the term 'Apache' to maintain consistency in the translation.

There is no sense in translating `Apache`, just as there is no sense in translating `NGINX`, `Composer`, etc.

> **Best practice**
> Use '%d' for numeric placeholders to improve clarity in messages involving numbers.

On line 68, the `menuChangePort` key should not contain `%d`, as in [other translations](https://github.com/Bearsampp/Bearsampp/blob/a831407a334a797d9e92f84143cc2f55c5c15a31/core/langs/english.lng#L68).

> **Bug**
> Correct the spelling mistake for better accuracy and professionalism.

In lines 132-134 I did make a typo and I admit it.
Errors corrected.

Could you please advise me if I can make a second commit with corrections in this PR?
Thanks!

**Comment by jwaisner** [comment]
@cosmopolityan , yes you can make a second commit to the branch and then push. It will  update your PR here.

Thank you for taking the time to review these suggestions!

**Comment by N6REJ** [comment]
please remove nginx and let us know which line number so we can update the rest of the lang files.  We don't support nginx anymore

**Comment by cosmopolityan** [comment]
> @cosmopolityan , yes you can make a second commit to the branch and then push. It will update your PR here.
> 
> Thank you for taking the time to review these suggestions!

Ok, thank you!

**Comment by cosmopolityan** [comment]
> please remove nginx and let us know which line number so we can update the rest of the lang files. We don't support nginx anymore

I apologize about the nginx. It was a conditional example.
It is certainly not in the files.

**Review by N6REJ — APPROVED** [review]

**Comment by N6REJ** [comment]
when I change to russian I get lots of white space. @cosmopolityan do you know why that might be?
image
image

**Comment by cosmopolityan** [comment]
> when I change to russian I get lots of white space. @cosmopolityan do you know why that might be? 

It's strange, because UTF-8 is used everywhere... I think the problem is in the character encoding or conversion at some stage... Because it's Cyrillic, it's not displayed for some reason.
Unfortunately I don't have a possibility to see the software at work right now on my machine.

**Pull request merged**
